version: '3'

services:
    postgres:
        image: postgres
        container-name: finance-app-postgres
        environment:
            POSTGRES_PASSWORD:
            POSTGRES_USER:
            POSTGRES_DB: financeapp
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
