services:
    postgres:
        image: postgres
        container_name: finance-app
        environment:
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: financeapp
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data

    postgres-test:
        image: postgres
        container_name: finance-app-test
        environment:
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: financeapp-db-test
        ports:
            - '5433:5433'
