name: Deploy

on:
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: ESLint
              uses: npm run eslint:check

            - name: Prettier
              uses: npm run prettier:check

            - name: Test
              uses: npm run test
